# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.api.lens_api import LensApi


class TestLensApi(unittest.IsolatedAsyncioTestCase):
    """LensApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LensApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_lens_graph(self) -> None:
        """Test case for lens_graph

        Query the Lens graph
        """
        pass


if __name__ == '__main__':
    unittest.main()
