# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.models.prefill_response import PrefillResponse

class TestPrefillResponse(unittest.TestCase):
    """PrefillResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrefillResponse:
        """Test PrefillResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrefillResponse`
        """
        model = PrefillResponse()
        if include_optional:
            return PrefillResponse(
                session_id = '',
                status = 'match',
                individual = None,
                evaluation = fideo_api.models.prefill_evaluation.PrefillEvaluation(
                    risk = 1.337, 
                    checks = [
                        fideo_api.models.check_result.CheckResult(
                            id = '', 
                            state = '', 
                            name = '', 
                            description = '', 
                            risk = 'HIGH', 
                            check_package = '', )
                        ], )
            )
        else:
            return PrefillResponse(
                session_id = '',
                status = 'match',
        )
        """

    def testPrefillResponse(self):
        """Test PrefillResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
