# coding: utf-8

"""
    Fideo Production API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.api.beta_api import BetaApi


class TestBetaApi(unittest.TestCase):
    """BetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BetaApi()

    def tearDown(self) -> None:
        pass

    def test_beta_signals_patterns_summary_post(self) -> None:
        """Test case for beta_signals_patterns_summary_post

        Get signal patterns summary
        """
        pass

    def test_beta_signals_patterns_timeseries_post(self) -> None:
        """Test case for beta_signals_patterns_timeseries_post

        Get signal patterns timeseries
        """
        pass


if __name__ == '__main__':
    unittest.main()
