# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.api.beta_api import BetaApi


class TestBetaApi(unittest.IsolatedAsyncioTestCase):
    """BetaApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BetaApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_signal_patterns_summary(self) -> None:
        """Test case for get_signal_patterns_summary

        Get signal patterns summary
        """
        pass

    async def test_get_signal_patterns_timeseries(self) -> None:
        """Test case for get_signal_patterns_timeseries

        Get signal patterns timeseries
        """
        pass


if __name__ == '__main__':
    unittest.main()
