# coding: utf-8

"""
    Fideo Production API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.models.signal_pattern_recency_response import SignalPatternRecencyResponse

class TestSignalPatternRecencyResponse(unittest.TestCase):
    """SignalPatternRecencyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignalPatternRecencyResponse:
        """Test SignalPatternRecencyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignalPatternRecencyResponse`
        """
        model = SignalPatternRecencyResponse()
        if include_optional:
            return SignalPatternRecencyResponse(
                hour = fideo_api.models.signal_pattern_response_unit.SignalPatternResponseUnit(
                    observations = 56, 
                    sources = 56, 
                    events = [
                        fideo_api.models.signal_pattern_response_unit_count.SignalPatternResponseUnitCount(
                            type = '', 
                            observations = 56, 
                            sources = 56, )
                        ], ),
                day = fideo_api.models.signal_pattern_response_unit.SignalPatternResponseUnit(
                    observations = 56, 
                    sources = 56, 
                    events = [
                        fideo_api.models.signal_pattern_response_unit_count.SignalPatternResponseUnitCount(
                            type = '', 
                            observations = 56, 
                            sources = 56, )
                        ], ),
                week = fideo_api.models.signal_pattern_response_unit.SignalPatternResponseUnit(
                    observations = 56, 
                    sources = 56, 
                    events = [
                        fideo_api.models.signal_pattern_response_unit_count.SignalPatternResponseUnitCount(
                            type = '', 
                            observations = 56, 
                            sources = 56, )
                        ], ),
                month = fideo_api.models.signal_pattern_response_unit.SignalPatternResponseUnit(
                    observations = 56, 
                    sources = 56, 
                    events = [
                        fideo_api.models.signal_pattern_response_unit_count.SignalPatternResponseUnitCount(
                            type = '', 
                            observations = 56, 
                            sources = 56, )
                        ], ),
                six_month = fideo_api.models.signal_pattern_response_unit.SignalPatternResponseUnit(
                    observations = 56, 
                    sources = 56, 
                    events = [
                        fideo_api.models.signal_pattern_response_unit_count.SignalPatternResponseUnitCount(
                            type = '', 
                            observations = 56, 
                            sources = 56, )
                        ], ),
                year = fideo_api.models.signal_pattern_response_unit.SignalPatternResponseUnit(
                    observations = 56, 
                    sources = 56, 
                    events = [
                        fideo_api.models.signal_pattern_response_unit_count.SignalPatternResponseUnitCount(
                            type = '', 
                            observations = 56, 
                            sources = 56, )
                        ], )
            )
        else:
            return SignalPatternRecencyResponse(
        )
        """

    def testSignalPatternRecencyResponse(self):
        """Test SignalPatternRecencyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
