# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.api.prefill_api import PrefillApi


class TestPrefillApi(unittest.IsolatedAsyncioTestCase):
    """PrefillApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PrefillApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_prefill(self) -> None:
        """Test case for prefill

        Resolve or evaluate onboarding identity fields
        """
        pass


if __name__ == '__main__':
    unittest.main()
