# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.models.status_response_with_message import StatusResponseWithMessage

class TestStatusResponseWithMessage(unittest.TestCase):
    """StatusResponseWithMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusResponseWithMessage:
        """Test StatusResponseWithMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusResponseWithMessage`
        """
        model = StatusResponseWithMessage()
        if include_optional:
            return StatusResponseWithMessage(
                message = '',
                status = 56,
                code = ''
            )
        else:
            return StatusResponseWithMessage(
        )
        """

    def testStatusResponseWithMessage(self):
        """Test StatusResponseWithMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
