# coding: utf-8

"""
    Fideo Production API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fideo_api.models.beta_signals_patterns_summary_post400_response import BetaSignalsPatternsSummaryPost400Response

class TestBetaSignalsPatternsSummaryPost400Response(unittest.TestCase):
    """BetaSignalsPatternsSummaryPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetaSignalsPatternsSummaryPost400Response:
        """Test BetaSignalsPatternsSummaryPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetaSignalsPatternsSummaryPost400Response`
        """
        model = BetaSignalsPatternsSummaryPost400Response()
        if include_optional:
            return BetaSignalsPatternsSummaryPost400Response(
                error = ''
            )
        else:
            return BetaSignalsPatternsSummaryPost400Response(
        )
        """

    def testBetaSignalsPatternsSummaryPost400Response(self):
        """Test BetaSignalsPatternsSummaryPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
