# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from fideo_api.models.multi_field_req_with_options import MultiFieldReqWithOptions
from fideo_api.models.prefill_evaluation import PrefillEvaluation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PrefillResponse(BaseModel):
    """
    PrefillResponse
    """ # noqa: E501
    session_id: UUID = Field(description="UUIDv7 session identifier to send with reviewed identity data.", alias="sessionId")
    status: StrictStr
    individual: Optional[MultiFieldReqWithOptions] = Field(default=None, description="Resolved identity in the same multifield shape accepted by the follow-up Prefill request. The caller may review or edit these values and resubmit them with the returned sessionId.")
    evaluation: Optional[PrefillEvaluation] = None
    __properties: ClassVar[List[str]] = ["sessionId", "status", "individual", "evaluation"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['match', 'no_match']):
            raise ValueError("must be one of enum values ('match', 'no_match')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrefillResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of individual
        if self.individual:
            _dict['individual'] = self.individual.to_dict()
        # override the default output from pydantic by calling `to_dict()` of evaluation
        if self.evaluation:
            _dict['evaluation'] = self.evaluation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrefillResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessionId": obj.get("sessionId"),
            "status": obj.get("status"),
            "individual": MultiFieldReqWithOptions.from_dict(obj["individual"]) if obj.get("individual") is not None else None,
            "evaluation": PrefillEvaluation.from_dict(obj["evaluation"]) if obj.get("evaluation") is not None else None
        })
        return _obj


