# coding: utf-8

"""
    Fideo Production API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from fideo_api.models.signal_pattern_response_unit import SignalPatternResponseUnit
from typing import Optional, Set
from typing_extensions import Self

class SignalPatternRecencyResponse(BaseModel):
    """
    SignalPatternRecencyResponse
    """ # noqa: E501
    hour: Optional[SignalPatternResponseUnit] = None
    day: Optional[SignalPatternResponseUnit] = None
    week: Optional[SignalPatternResponseUnit] = None
    month: Optional[SignalPatternResponseUnit] = None
    six_month: Optional[SignalPatternResponseUnit] = Field(default=None, alias="sixMonth")
    year: Optional[SignalPatternResponseUnit] = None
    __properties: ClassVar[List[str]] = ["hour", "day", "week", "month", "sixMonth", "year"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SignalPatternRecencyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hour
        if self.hour:
            _dict['hour'] = self.hour.to_dict()
        # override the default output from pydantic by calling `to_dict()` of day
        if self.day:
            _dict['day'] = self.day.to_dict()
        # override the default output from pydantic by calling `to_dict()` of week
        if self.week:
            _dict['week'] = self.week.to_dict()
        # override the default output from pydantic by calling `to_dict()` of month
        if self.month:
            _dict['month'] = self.month.to_dict()
        # override the default output from pydantic by calling `to_dict()` of six_month
        if self.six_month:
            _dict['sixMonth'] = self.six_month.to_dict()
        # override the default output from pydantic by calling `to_dict()` of year
        if self.year:
            _dict['year'] = self.year.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SignalPatternRecencyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hour": SignalPatternResponseUnit.from_dict(obj["hour"]) if obj.get("hour") is not None else None,
            "day": SignalPatternResponseUnit.from_dict(obj["day"]) if obj.get("day") is not None else None,
            "week": SignalPatternResponseUnit.from_dict(obj["week"]) if obj.get("week") is not None else None,
            "month": SignalPatternResponseUnit.from_dict(obj["month"]) if obj.get("month") is not None else None,
            "sixMonth": SignalPatternResponseUnit.from_dict(obj["sixMonth"]) if obj.get("sixMonth") is not None else None,
            "year": SignalPatternResponseUnit.from_dict(obj["year"]) if obj.get("year") is not None else None
        })
        return _obj


