# coding: utf-8

"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from fideo_api.models.check_result import CheckResult
from fideo_api.models.evidence import Evidence
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VerifyResponse(BaseModel):
    """
    VerifyResponse
    """ # noqa: E501
    risk: Optional[Union[StrictFloat, StrictInt]] = None
    checks: Optional[List[CheckResult]] = None
    session_id: Optional[UUID] = Field(default=None, alias="sessionId")
    address_line1: Optional[StrictStr] = Field(default=None, alias="addressLine1")
    address_line2: Optional[StrictStr] = Field(default=None, alias="addressLine2")
    city: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    region_code: Optional[StrictStr] = Field(default=None, alias="regionCode")
    country: Optional[StrictStr] = None
    continent: Optional[StrictStr] = None
    postal_code: Optional[StrictStr] = Field(default=None, alias="postalCode")
    family_name: Optional[StrictStr] = Field(default=None, alias="familyName")
    given_name: Optional[StrictStr] = Field(default=None, alias="givenName")
    full_name: Optional[StrictStr] = Field(default=None, alias="fullName")
    phone: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    social: Optional[StrictStr] = None
    ip_address: Optional[StrictStr] = Field(default=None, alias="ipAddress")
    birthday: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    organization: Optional[StrictStr] = None
    evidence: Optional[Evidence] = None
    __properties: ClassVar[List[str]] = ["risk", "checks", "sessionId", "addressLine1", "addressLine2", "city", "region", "regionCode", "country", "continent", "postalCode", "familyName", "givenName", "fullName", "phone", "email", "social", "ipAddress", "birthday", "title", "organization", "evidence"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VerifyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in checks (list)
        _items = []
        if self.checks:
            for _item_checks in self.checks:
                if _item_checks:
                    _items.append(_item_checks.to_dict())
            _dict['checks'] = _items
        # override the default output from pydantic by calling `to_dict()` of evidence
        if self.evidence:
            _dict['evidence'] = self.evidence.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VerifyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "risk": obj.get("risk"),
            "checks": [CheckResult.from_dict(_item) for _item in obj["checks"]] if obj.get("checks") is not None else None,
            "sessionId": obj.get("sessionId"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "city": obj.get("city"),
            "region": obj.get("region"),
            "regionCode": obj.get("regionCode"),
            "country": obj.get("country"),
            "continent": obj.get("continent"),
            "postalCode": obj.get("postalCode"),
            "familyName": obj.get("familyName"),
            "givenName": obj.get("givenName"),
            "fullName": obj.get("fullName"),
            "phone": obj.get("phone"),
            "email": obj.get("email"),
            "social": obj.get("social"),
            "ipAddress": obj.get("ipAddress"),
            "birthday": obj.get("birthday"),
            "title": obj.get("title"),
            "organization": obj.get("organization"),
            "evidence": Evidence.from_dict(obj["evidence"]) if obj.get("evidence") is not None else None
        })
        return _obj


